name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Run poetry install
        run: poetry install

      - name: Lint
        run: |
          echo "::add-matcher::.github/workflows/flake8-problem-matcher.json"
          poetry run python -m flake8 .
